### ISSUE TITLE
Custom type name lookup not working

### ISSUE THREAD

**Issue by RealSilo** [ashkan18/graphlient#54]
I have a query working with `graphql` but not with `graphlient` because of the naming  of the type.

I tried to investigate the issue but it went down pretty deep (graphql-client gem) and couldn't figure out why it works with a simple` graphql` query and why not with `graphlient`.

Do you have any ideas where this goes wrong?

The error is the following (It tries to lookup `Vehicle`, but it should lookup `VehicleType`).

```
   Failure/Error: response = client.execute(vehicle_query, id: vehicle.id)

     Graphlient::Errors::ClientError:
       Field 'vehicle_alerts' doesn't exist on type 'Vehicle'
     # /Users/silo/Desktop/carforce/gems/graphlient/lib/graphlient/client.rb:32:in `rescue in execute'
     # /Users/silo/Desktop/carforce/gems/graphlient/lib/graphlient/client.rb:20:in `execute'
     # ./spec/graphql/queries/vehicle_query_spec.rb:49:in `block (5 levels) in <top (required)>'
     # ./spec/rails_helper.rb:72:in `block (3 levels) in <top (required)>'
     # /Users/silo/.rvm/gems/ruby-2.5.1/gems/database_cleaner-1.7.0/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # /Users/silo/.rvm/gems/ruby-2.5.1/gems/database_cleaner-1.7.0/lib/database_cleaner/base.rb:100:in `cleaning'
     # /Users/silo/.rvm/gems/ruby-2.5.1/gems/database_cleaner-1.7.0/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # /Users/silo/.rvm/gems/ruby-2.5.1/gems/database_cleaner-1.7.0/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/rails_helper.rb:71:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # GraphQL::Client::ValidationError:
     #   Field 'vehicle_alerts' doesn't exist on type 'Vehicle'
     #   /Users/silo/Desktop/carforce/gems/graphlient/lib/graphlient/client.rb:29
```
See my classes the and the queries below:

```
field :vehicle_lookup,
          resolver: Queries::VehicleLookupQuery,
          description: 'Vehicle from lookup service without ID',
          authenticate: true
```

```
module Queries
  class VehicleQuery < Queries::BaseQuery
    type Types::VehicleType, null: false
    argument :id, String, 'id', required: true

    def resolve(id:)
      Vehicle.find(id)
    end
  end
end
```

```
module Types
  class VehicleType < GraphQL::Schema::Object
    field :id, ID, 'Primary key', null: false
    field :make, String, 'Make', null: false
    field :vehicle_alerts,
          [Types::VehicleAlertType],
          'Vehicle Alerts',
          null: false do
      argument :state, String, 'state', required: false
    end

    def vehicle_alerts(state: 'active')
      HasManyLoader.for(
        VehicleAlert, :vehicle_id, where_options: { state: state }
      ).load(object.id)
    end
  end
end
```

See graplient and gql queries below:

    let(:vehicle_query) do
      <<-GRAPHQL
        query($id: String!) {
          vehicle(id: $id) {
            id
            make
            vehicle_alerts {
              id
            }
          }
        }
      GRAPHQL
    end

This works from any FE/graphql interface (graphiql, etc.)

```
const vehicleQuery = gql`
  query($id: String!) {
    vehicle(id: $id) {
      id
      make
      vehicleAlerts {
        id
      }
    }
  }
`;
```

**Comment by yuki24** [comment]
Have you tried replacing the `vehicle_alerts` field in the `let(:vehicle_query)` with `vehicleAlerts`?

**Comment by RealSilo** [comment]
Yeah, that's it. Thx!
